### ISSUE TITLE
ksVirtualListView memory Leaks

### ISSUE THREAD

**Issue by frankwu-delphi** [gmurt/PentireFMX#5]
hi，
in ksVirtualListView, if drag item show delete-button, and click delete-button to delete a TksVListItem, close exe, it show memory leaks.
delphi 10.4.2 + windows 10 x64

demo code:
[Action Buttons.zip](https://github.com/gmurt/PentireFMX/files/7147310/Action.Buttons.zip)

screensnaps:
![001](https://user-images.githubusercontent.com/54831748/132938553-fdf31a82-c73c-4c47-b115-4c7755ce0a1e.png)
![002](https://user-images.githubusercontent.com/54831748/132938558-37ce33c7-6d5f-4af0-94fb-7e113778a171.png)

**Comment by marlonnardi** [comment]
@gmurt

**Comment by gmurt** [comment]
Apologies for the delay.  Fixed in latest commit
